--- 
common: &common
  aws_access_key_id: AKIAJX42NHHAZDUPKPBQ
  aws_secret_access_key: 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

development:
  <<: *common

  # Uncomment and I only apply to the dev environment
  # or overwrite a common value
  #foo: 'bar'

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common

  # Uncomment and I only apply to the production environment
  # or overwrite a common value
  #foo: 'baz'
