--- 
- :version: = 0.4.5
  :name: httparty
- :name: crack
- :source: http://gems.github.com
  :name: javan-whenever
- :source: http://gems.github.com
  :name: josevalim-rails-footnotes
- :version: 2.3.3
  :name: rails
