:ruby: ree
:user: rails

#############################################################
#	Settings
#############################################################
:default_run_options:
  :pty: true
#:ssh_options:
#  :forward_agent: true
:use_sudo: true
:scm_verbose: true

:deploy_to: /srv/putyourselfon
  
#############################################################
#	Git
#############################################################
:scm: :git
:repository: git@github.com:highgroove/pyo.git
:deploy_via: remote_cache
:keep_releases: 20

#:time_zone: UTC
#:domain_aliases:
#  - assets1.yourapp.com
#  - assets2.yourapp.com

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
  - uploads
  - data
  - stylesheets/pyo
#
# Use :shared_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:shared_config:
  - config/database.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
  - system
  - log
  - pids
  - config
  - public/stylesheets
  - public/stylesheets/pyo

# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
#:apt_gems:
#  :awesomegem:
#    - awesome
#    - libawesome-dev
#
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :version: 3.0.4
  :max_pool_size: 3
  :use_global_queue: true
:mysql:
  :innodb_buffer_pool_size: 128M
  
