# PYO
access_key_id: AKIAJX42NHHAZDUPKPBQ
secret_access_key: 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

# digital scientists
# access_key_id: 0D0E3D1A30NERF3G24G2
# secret_access_key: AB5ZyKvp6YQ5xuKAM4hu0DvQxGZIj+/FyBpeuKRy